# Specifies how to access the content for your site, including authentication.
# Full details and code samples: https://t.ly/VZ3Zd
backend:
  name: github
  branch: feature/cms-setup # Branch that the CMS will publish to
  repo: yisraelgrimes/gatsby-boilerplate

# Allow for drafting, reviewing, approving posts
# Only available for Github
# publish_mode: editorial_workflow

# CMS users can upload files to the repo using the Media Gallery to the 'media_folder'.
media_folder: static/images
# Those uploaded files can be accessed on the published site at 'public_folder'
public_folder: /img

# URL of the published site
# site_url: https://your-site.com

# When specified, the CMS UI will include a link in the fixed area at the top of the page, allowing content authors to easily return to your main site.
display_url: localhost:8000

# When specified, the CMS UI will change the logo displayed at the top of the login page
# logo_url: https://your-site.com/images/logo.svg

# Folder Collection: Users can create/delete new items based on a template
collections:
  - name: "posts" # Post-type identifier, used in routes, e.g., /admin/collections/blog (must be unique)
    label: "Posts" # The UI name in the main 'Collections' menu
    description: "Description of the collection. Displayed below the label when viewing a collection. Optional." # Optional. Shown with the label in the UI.
    folder: "data/content/posts" # Where the CMS stores new documents in the collection.
    create: true # Users can create items in the collection; defaults to false
    delete: true # Users can delete items in the collection; defaults to true
    # slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Also used for naming the file; Must be unique.
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Template", name: "template", widget: "string", default: "post" }
      - { label: "Publish Date", name: "date", widget: "date" }
      - { label: "Body", name: "body", widget: "markdown" }

  # Folder Collection
  - name: "pages" # Post-type identifier, used in routes, e.g., /admin/collections/blog (must be unique)
    label: "Pages" # The UI name in the main 'Collections' menu
    description: "Description of the collection. Displayed below the label when viewing a collection. Optional." # Optional. Shown with the label in the UI.
    folder: "data/content/pages" # Where the CMS stores new documents in the collection.
    create: true # Users can create items in the collection; defaults to false
    delete: true # Users can delete items in the collection; defaults to true
    # slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Also used for naming the file; Must be unique.
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Template", name: "template", widget: "string", default: "page" }
      - { label: "Show Sidebar", name: "sidebar", widget: "boolean", default: false }
      - { label: "Publish Date", name: "date", widget: "date" }
      - { label: "Body", name: "body", widget: "markdown" }

  # File Collections (Unique Documents)
  # Can only be updated, not created or removed
  - name: "uniquePages"
    label: "Unique Pages"
    files:
      # Home Page
      - file: "data/content/index.md" # Location of File
        label: "Home Page" # Shown in the 'Pages' collection-list
        name: "index"
        fields:
          - { label: "Title", name: "title", widget: "string", default: "Home Page" }
          - { label: "Template", name: "template", widget: "string", default: "home" }
          - { label: "Publish Date", name: "date", widget: "date" }
          - { label: "Body", name: "body", widget: "markdown" }
      # Blog Page
      - file: "data/content/blog.md" # Location of File
        label: "Blog" # Shown in the 'Pages' collection-list
        name: "blog"
        fields:
          - { label: "Title", name: "title", widget: "string", default: "Blog Index Page" }
          - { label: "Template", name: "template", widget: "string", default: "blog-index" }
          - { label: "Show Sidebar", name: "sidebar", widget: "boolean", default: true }
          - { label: "Publish Date", name: "date", widget: "date" }
          - { label: "Number of Posts to show on the main page.", name: "postCount", widget: "number", default: 10 }
          - { label: "Body", name: "body", widget: "markdown" }

  # Settings Collections
  - name: "settings"
    label: "Settings"
    extension: "yml"
    files:
      # Site Meta
      - file: "data/settings/siteMeta/siteMeta.yml"
        label: "Site MetaData"
        name: "siteMeta"
        fields:
          - { label: "Site Title", name: "title", widget: "string", required: true }
          - { label: "Site URL", name: "title", widget: "string", default: "https://www.example.com", required: true }
          - { label: "Site Description", name: "description", widget: "text" }
          # TODO: Might add a relation widget for the default author and link to an 'authors' page
          - { label: "Default Content Author", name: "defaultAuthor", widget: "string", default: "Bob Ross" }
          - label: "Advanced Settings"
            name: "manifest"
            widget: "object"
            fields:
              - { label: "Project Name", name: "name", widget: "string", default: "gatsby-boilerplate", required: true }
              - { label: "Project Short-Name", name: "shortName", widget: "string", default: "boilerplate", required: true }
              - { label: "Background Color", name: "backgroundColor", widget: "string", default: "#333333", required: true }
              - { label: "Theme Color", name: "themeColor", widget: "string", default: "#333333", required: true }
              - { label: "Display Style", name: "display", widget: "string", default: "minimal-ui", required: true }
              - { label: "Icon File", name: "icon", widget: "string", default: "data/img/icon-dark.png", required: true }
              # TODO: Instead of a string, we should make this an image-type

      # Main Navigation
      - file: "data/settings/mainNav/mainNav.yml"
        label: "Site Navigation"
        name: "mainNav"
        fields:
          - label: "Menu Items"
            name: "menu"
            widget: "list"
            fields:
              - { label: "Menu Title", name: "title", widget: "string", default: "Contact Us", required: true }
              - { label: "Path to Page", name: "path", widget: "string", default: "/contact-us", required: true }
              # TODO: Instead of a string, we might be able to make this relational

      # Sidebar
      - file: "data/settings/sidebar/sidebar.yml"
        label: "Sidebar"
        name: "sidebar"
        fields:
          - label: "Recent Posts Section"
            name: "recentPosts"
            widget: "object"
            fields:
              - { label: "Show Recent Posts", name: "visible", widget: "boolean", default: true }
              - { label: "Section Heading", name: "heading", widget: "string", default: "Recent Posts" }
              - { label: "Number of posts to display", name: "count", widget: "number", default: 5 }
          - label: "Featured Links Section"
            name: "featured"
            widget: "object"
            fields:
              - { label: "Show Featured Links", name: "visible", widget: "boolean", default: true }
              - { label: "Section Heading", name: "heading", widget: "string", default: "Notable Links" }
              - label: "Links"
                name: "links"
                widget: "list"
                fields:
                  - { label: "Link Name", name: "title", widget: "string", default: "Facebook", required: true }
                  - { label: "Full URL", name: "path", widget: "string", default: "https://facebook.com", required: true }

      # Footer
      - file: "data/settings/footer/footer.yml"
        label: "Footer"
        name: "footer"
        fields:
          - label: "Extra Navigation Section"
            name: "navigation"
            widget: "object"
            fields:
              - { label: "Show Section", name: "visible", widget: "boolean", default: true }
              - { label: "Section Heading", name: "heading", widget: "string", default: "Site Navigation" }
              - label: "Menu Items"
                name: "links"
                widget: "list"
                fields:
                  - { label: "Menu Name", name: "title", widget: "string", default: "Contact-Us", required: true }
                  - { label: "Path to Page", name: "path", widget: "string", default: "/contact-us", required: true }
          - label: "Social Media"
            name: "social"
            widget: "object"
            fields:
              - { label: "Show Section", name: "visible", widget: "boolean", default: true }
              - { label: "Section Heading", name: "heading", widget: "string", default: "Get Social" }
              - label: "Links"
                name: "links"
                widget: "list"
                fields:
                  - { label: "Link Name", name: "title", widget: "string", default: "Facebook", required: true }
                  - { label: "Full URL", name: "path", widget: "string", default: "https://facebook.com", required: true }